version: '3.8'

services:
  # PostgreSQL Database (Latest Stable Version)
  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

  # Hazelcast (Latest Stable Version)
  hazelcast-order:
    image: hazelcast/hazelcast:5.3.5
    container_name: hazelcast-order
    ports:
      - "5702:5701"
    environment:
      HZ_NETWORK_PORT: 5702
      HZ_CLUSTER_NAME: dev
    networks:
      - order-network

  # Spring Boot Application
  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_HAZELCAST_NETWORK_MEMBERS: hazelcast-order:5702
      JWT_SECRET_KEY: 5PLwtPwpfCqxNQQmpwp2NBoRFru5C1b1taijGkWuSw5kGd6gbgcVj7b7e0CPJ1UQBRK2t/+qChLXRSaf/l0Ulg==
    depends_on:
      - postgres-order
      - hazelcast-order
    networks:
      - app-network
      - order-network

volumes:
  postgres_data:
networks:
  app-network:
    external: true
  order-network:
    driver: bridge